### PR TITLE
Update Licenses

### PR DESCRIPTION
**Pull request by colinnielsen**

### CODE REVIEW

**Comment by colinnielsen** [comment]
@Mike-Revy any update on this?

**Comment by Mike-Revy** [comment]
I thought we were doing same thing as UniSwap? 
    On Thursday, December 8, 2022 at 09:42:06 AM MST, Colin Nielsen ***@***.***> wrote:  
 
 


@Mike-Revy any update on this?

**Comment by colinnielsen** [comment]
> I thought we were doing same thing as UniSwap?

Great yep. This should match their repo.

**Pull request merged**
